### PR TITLE
#13 Adds script to accept and close cookies modal on appsloveworld

### PR DESCRIPTION
**Pull request by iamplugged**
https://github.com/Screenly/playground/issues/13

- Adds a script to accept cookies and close consent modal

Pending:
- Readme Update (Waiting for confirmation if this is specifically required to be run on appsloveworld)

### CODE REVIEW

**Comment by vpetersson** [comment]
Ok, I know this is beyond the scope of the initial ticket, but could you:

* Find out what this cookie consent form is called and document it (rather than appsloveworld). This is a common one that is used across a lot of different 
* Find out what the cookie consent form for Engadget is called (and document it). I think the Engadget one is probably an internal Yahoo product.

**Comment by iamplugged** [comment]
@vpetersson 

- The appsloveworld one is called ez-cookie. I could find some scripts using it. But I couldn't find the actual product.
- The Engadget one as you have mentioned can be seen on Yahoo/AOL/Verizon properties - AOL, Techcrunch etc.

**Review by rusko124 — APPROVED** [review]

**Comment by vpetersson** [comment]
> @vpetersson
> 
>     * The appsloveworld one is called ez-cookie. I could find some scripts using it. But I couldn't find the actual product.
> 
>     * The Engadget one as you have mentioned can be seen on Yahoo/AOL/Verizon properties - AOL, Techcrunch etc.

Great. Please update the README accordingly.

**Comment by iamplugged** [comment]
Updated. Could not find a logo for ez-cookie though.

**Comment by iamplugged** [comment]
Awaiting https://github.com/Screenly/playground/pull/15 to get merged before lint issues can be resolved.

**Pull request merged**
