### PR TITLE
Fix bugs in clock app #109

### PR DESCRIPTION
**Pull request by salmanfarisvp**
Fixed issue mentioned here https://github.com/Screenly/Playground/issues/109 

- [X] Use MMMM DD YYYY Date Format 
- [X]  Use 24 hr Format 

image

### CODE REVIEW

**Comment by vpetersson** [comment]
Nice one @salmanfarisvp. However, we shouldn't hard code 24h clock. It should be based on the locale.

**Comment by salmanfarisvp** [comment]
Thanks @vpetersson,  Updated it to use as per the locate :) .

**Comment by salmanfarisvp** [comment]
@vpetersson Can you guide me on how it should be the expected output?  

The old `momentObject.format('LT')` will use 2:30 AM and use the 24-hour when using a non-English locale depending it.

**Comment by salmanfarisvp** [comment]
This PR closed by discussion with @nicomiguelino , The Issue already solved and  feature already implement in https://github.com/Screenly/Playground/pull/121

**Pull request closed without merging**
